name: Tin Empire
favicon: null
layout_spectrum: 0.94005
typography_spectrum: 0.29439
title: 'Industrial Americana Duo - Denver, Colorado USA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
